In [1]:
import torch

In [2]:
x = [2, 9, 5, 16, 23, 35]

In [3]:
# 1 检查x是否为tensor对象
torch.is_tensor(x)

False

In [4]:
y = torch.rand(1, 2) # 1行2列
y

tensor([[0.9433, 0.3230]])

In [5]:
torch.is_tensor(y)

True

In [6]:
torch.numel(y) # 统计tensor中的元素个数

2

In [7]:
# 创建全0的tensor
z = torch.zeros(3,3) # 3行3列
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.numel(z)

9

In [9]:
# 3 创建对角线为1的tensor
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
# 4将numpy转换为tensor
import numpy as np

In [11]:
x = np.array([3,4,5,6,7])
x

array([3, 4, 5, 6, 7])

In [12]:
torch.from_numpy(x)

tensor([3, 4, 5, 6, 7])

In [13]:
# 5 切分 linspace
torch.linspace(2, 10, steps=5) # 起始是2，终止是10，切5份

tensor([ 2.,  4.,  6.,  8., 10.])

In [14]:
# 6 均匀分布，值在0和1之间
torch.rand(10)

tensor([0.5103, 0.6951, 0.6761, 0.7729, 0.4048, 0.2640, 0.5029, 0.7753, 0.7585,
        0.3892])

In [15]:
# 7 正态分布，均值为0，方差为1
x = torch.randn(10)
x

tensor([-0.0327,  0.3569, -0.9496, -0.4575, -0.8760, -0.6890, -0.3171,  0.6391,
         1.8759,  2.1479])

In [16]:
# 8 选择随机数
torch.randperm(10)

tensor([8, 9, 0, 4, 5, 7, 6, 2, 1, 3])

In [17]:
# 9 生成一个区间的数
torch.arange(10, 30, 5), # 开始，结尾，步长

(tensor([10, 15, 20, 25]),)

In [24]:
# 10 获取行或列的最小值和最大值的索引
r = torch.randint(1,99, (3,3)), # 元素范围1～99，3行3列
r

(tensor([[69, 50, 75],
         [26, 82, 63],
         [71, 88, 57]]),)

In [25]:
torch.is_tensor(r)

False

In [26]:
torch.is_tensor(r)

False

In [27]:
z = torch.rand(3,5)

In [28]:
z

tensor([[0.8312, 0.9551, 0.5536, 0.6129, 0.1993],
        [0.3767, 0.4639, 0.7810, 0.0048, 0.8752],
        [0.0036, 0.0900, 0.2358, 0.9270, 0.3053]])

In [29]:
torch.is_tensor(z)

True