In [1]:
import torch

In [2]:
x = [2, 9, 5, 16, 23, 35]

In [3]:
# 1 检查x是否为tensor对象
torch.is_tensor(x)

False

In [4]:
y = torch.rand(1, 2) # 1行2列
y

tensor([[0.3008, 0.6378]])

In [5]:
torch.is_tensor(y)

True

In [6]:
torch.numel(y) # 统计tensor中的元素个数

2

In [7]:
# 创建全0的tensor
z = torch.zeros(3,3) # 3行3列
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.numel(z)

9

In [9]:
# 3 创建对角线为1的tensor
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
# 4将numpy转换为tensor
import numpy as np

In [11]:
x = np.array([3,4,5,6,7])
x

array([3, 4, 5, 6, 7])

In [12]:
torch.from_numpy(x)

tensor([3, 4, 5, 6, 7])

In [13]:
# 5 切分 linspace
torch.linspace(2, 10, steps=5) # 起始是2，终止是10，切5份

tensor([ 2.,  4.,  6.,  8., 10.])

In [14]:
# 6 均匀分布，值在0和1之间
torch.rand(10)

tensor([0.5169, 0.5011, 0.6891, 0.7092, 0.3310, 0.3138, 0.5103, 0.2698, 0.9205,
        0.0771])

In [15]:
# 7 正态分布，均值为0，方差为1
x = torch.randn(10)
x

tensor([ 0.6548,  0.5867,  0.4916, -1.0868,  1.7859, -0.9599,  1.3224, -0.5550,
         0.7131, -0.0813])

In [16]:
# 8 选择随机数
torch.randperm(10)

tensor([9, 7, 5, 2, 8, 4, 3, 0, 1, 6])

In [17]:
# 9 生成一个区间的数
torch.arange(10, 30, 5), # 开始，结尾，步长

(tensor([10, 15, 20, 25]),)

In [18]:
# 10 获取行或列的最小值和最大值的索引
r = torch.randint(1,99, (3,3)), # 元素范围1～99，3行3列
r

(tensor([[22, 36, 15],
         [26, 39, 23],
         [ 6, 45, 97]]),)

In [20]:
torch.is_tensor(r)

False

In [21]:
torch.is_tensor(r)

False

In [22]:
z = torch.rand(3,5)

In [23]:
z

tensor([[0.8944, 0.5106, 0.7726, 0.8298, 0.8311],
        [0.3192, 0.5443, 0.3922, 0.0470, 0.2565],
        [0.2729, 0.9379, 0.2099, 0.5350, 0.6847]])

In [24]:
torch.is_tensor(z)

True

In [25]:
a = torch.randint(1, 99, size=(3,3))
print(a)

tensor([[16, 68,  3],
        [15, 80,  8],
        [ 3, 31, 83]])


In [26]:
print(torch.is_tensor(a))

True


In [27]:
b = torch.randint(1, 99, (3,3))
print(b)

tensor([[95, 10,  3],
        [29,  4,  7],
        [90, 50, 83]])


In [28]:
print(torch.is_tensor(b))

True


In [29]:
torch.argmin(b, dim=0) # 返回张量b中每列最小值的索引

tensor([1, 1, 0])

In [30]:
# 11 连接
x = torch.randint(1, 10, size=(2,3))
x

tensor([[9, 8, 6],
        [8, 5, 1]])

In [32]:
torch.cat((x,x))

tensor([[9, 8, 6],
        [8, 5, 1],
        [9, 8, 6],
        [8, 5, 1]])

In [33]:
torch.cat((x,x),dim=1) # 1是横轴

tensor([[9, 8, 6, 9, 8, 6],
        [8, 5, 1, 8, 5, 1]])

In [35]:
# 12 chunk 切块
a = torch.randint(1, 10, size=(3,3))
a

tensor([[2, 5, 1],
        [8, 7, 2],
        [4, 5, 1]])

In [36]:
torch.chunk(a, 2, 0) # 2是横向切，0是纵向切

(tensor([[2, 5, 1],
         [8, 7, 2]]),
 tensor([[4, 5, 1]]))

In [37]:
torch.chunk(a,2,1)

(tensor([[2, 5],
         [8, 7],
         [4, 5]]),
 tensor([[1],
         [2],
         [1]]))

In [38]:
# 13 index_select 根据索引选择
x = torch.randn(4,4)
x

tensor([[-0.4866, -0.3824, -0.0411, -0.5659],
        [ 2.0271,  1.2216, -1.0394, -0.2024],
        [ 0.4239,  0.7316,  0.3183, -0.8880],
        [-0.2469,  0.8867,  1.0403,  0.6877]])

In [39]:
index = torch.tensor([0,2]) # 创建一个索引，这个索引是一个1维张量，0是第0行，2是第2行

In [40]:
torch.index_select(x, 0, index)

tensor([[-0.4866, -0.3824, -0.0411, -0.5659],
        [ 0.4239,  0.7316,  0.3183, -0.8880]])

In [42]:
# 14 split 分割
x = torch.tensor([1,2,3,4,5,6,7])
x

tensor([1, 2, 3, 4, 5, 6, 7])

In [43]:
torch.split(x,3) 

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7]))

In [45]:
# 15 .t 和 .transpose 转置
x = torch.tensor([[1,2],[3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [46]:
x.t() # 转置

tensor([[1, 3],
        [2, 4]])

In [48]:
x.transpose(1,0)

tensor([[1, 3],
        [2, 4]])

In [49]:
# 16 tensor运算
x = torch.tensor([[1,2],[3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [50]:
torch.add(x,1)

tensor([[2, 3],
        [4, 5]])

In [51]:
torch.mul(x,2)

tensor([[2, 4],
        [6, 8]])