In [1]:
import torch

In [4]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [6]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [7]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [8]:
y.grad_fn

In [9]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [10]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
a.requires_grad

False

In [11]:
a.requires_grad_(True)

tensor([[ 6.7157, -5.0151],
        [ 1.1082,  2.1128]], requires_grad=True)

In [12]:
a.requires_grad

True

In [13]:
b = (a*a).sum()
b.grad_fn

In [14]:
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

True


In [16]:
out.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.