In [2]:
import numpy as np
import torch

# Import from numpy

In [2]:
a = np.array([2,3.3])

In [4]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [5]:
a=np.ones([2,3])

In [6]:
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

# Import from List

In [7]:
# 小写tensor和大写Tensor不同，小写的tensor接受的是具体的数据，即要么是numpy，要么是list。
# 大写的Tensor（FloatTensor，IntTensor等）接受的是shape，即数据维度，未初始化的数据类型
torch.tensor([2., 3.2])


tensor([2.0000, 3.2000])

In [8]:
# 大写的也可以接受具体数据，但要用[]包裹，表示是一个list
torch.FloatTensor([2.,3.2])

tensor([2.0000, 3.2000])

In [9]:
l = [3., 4., 5.]
l

[3.0, 4.0, 5.0]

In [10]:
a = torch.FloatTensor(l)

In [11]:
a

tensor([3., 4., 5.])

In [12]:
a.shape

torch.Size([3])

In [13]:
a.size(0)

3

In [14]:
a.shape[0]

3

# uninitialized

In [3]:
torch.empty(1)

tensor([0.])

In [7]:
torch.Tensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.Tensor(1)

tensor([0.])

In [11]:
torch.IntTensor(2,3)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [12]:
torch.FloatTensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# rand, [0,1]使用随机的0～1分布初始化值

In [14]:
a = torch.rand(3,3)

In [15]:
a

tensor([[0.1322, 0.5016, 0.0408],
        [0.6152, 0.0918, 0.2216],
        [0.5321, 0.4220, 0.3356]])

In [16]:
torch.rand_like(a)

tensor([[0.5312, 0.0192, 0.2848],
        [0.2432, 0.3024, 0.0825],
        [0.3738, 0.0861, 0.6364]])

In [26]:
torch.randint(1, 10,a.shape)

tensor([[7, 5, 5],
        [7, 3, 1],
        [1, 8, 3]])

In [24]:
a.shape

torch.Size([3, 3])

# randn, 正态分布N(0, 1)之间，N(u, std)

In [27]:
torch.randn(3,3)

tensor([[-0.4431, -1.7118,  0.0138],
        [-1.0520, -0.9175, -0.3809],
        [ 0.2526,  0.3437,  1.5512]])

# 指定全部是某个元素full

In [28]:
torch.full([2, 3],5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [30]:
a = torch.full([],7) # 生成标量

In [31]:
a

tensor(7)

In [32]:
a.shape

torch.Size([])

# arange/range

In [33]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
torch.arange(0, 10,2)

tensor([0, 2, 4, 6, 8])

# linspace/logspace

In [35]:
torch.linspace(0,10,steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [36]:
torch.linspace(0, 10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
torch.logspace(0,-1,steps=10) # logspace的base参数可以设置为2， 10， e等底数

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

# ones/zeros/eye

In [38]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [40]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

# randperm 打散

In [41]:
torch.rand(10)

tensor([0.3236, 0.7251, 0.3677, 0.2226, 0.0751, 0.3456, 0.5485, 0.3262, 0.4185,
        0.3424])

In [42]:
torch.randperm(10)

tensor([8, 0, 2, 1, 3, 5, 6, 9, 7, 4])

In [43]:
a = torch.rand(4, 3, 28, 28)

In [44]:
a[0].shape

torch.Size([3, 28, 28])

In [45]:
a[0,0].shape

torch.Size([28, 28])

In [46]:
a[0,0,2,4]

tensor(0.5502)