# Tensors（张量）

In [1]:
from __future__ import print_function
import torch

### 构造一个5*3矩阵，不初始化

In [2]:
x = torch.empty(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 构造一个随机初始化的矩阵

In [3]:
x = torch.rand(5,3)
x

tensor([[0.6503, 0.2318, 0.0734],
        [0.7849, 0.9109, 0.4711],
        [0.0290, 0.4550, 0.9422],
        [0.9055, 0.0723, 0.8480],
        [0.8217, 0.7343, 0.6461]])

### 构造一个矩阵全为0，类型long

In [4]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### 构造一个张量，直接使用数据

In [5]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [6]:
### 构造一个tensor基于已存在的tensor

In [8]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[ 1.5319,  0.4123, -0.1192],
        [-0.7041,  1.7259, -0.7056],
        [ 1.1667,  1.3898, -0.2715],
        [ 3.1119, -0.0400,  0.8284],
        [ 0.6990, -0.5484, -1.5246]])

### 获取维度信息

In [11]:
x.size()
# torch.Size是一个元组，支持左右的元组操作

torch.Size([5, 3])

### 加法1: x+y

In [18]:
y = torch.rand(5,3)
y

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


tensor([[0.7787, 0.1451, 0.1441],
        [0.0112, 0.5457, 0.0908],
        [0.1543, 0.4980, 0.7271],
        [0.5567, 0.6307, 0.7435],
        [0.2573, 0.1814, 0.5213]])

In [19]:
x+y

tensor([[ 2.3106,  0.5574,  0.0249],
        [-0.6929,  2.2716, -0.6148],
        [ 1.3210,  1.8878,  0.4557],
        [ 3.6686,  0.5907,  1.5719],
        [ 0.9564, -0.3670, -1.0033]])

### 加法2: torch.add(x,y)

In [21]:
torch.add(x,y)

tensor([[ 2.3106,  0.5574,  0.0249],
        [-0.6929,  2.2716, -0.6148],
        [ 1.3210,  1.8878,  0.4557],
        [ 3.6686,  0.5907,  1.5719],
        [ 0.9564, -0.3670, -1.0033]])

### 加法2: 提供一个输出tensor作为参数

In [22]:
result = torch.empty(5,3)
torch.add(x,y, out=result)

tensor([[ 2.3106,  0.5574,  0.0249],
        [-0.6929,  2.2716, -0.6148],
        [ 1.3210,  1.8878,  0.4557],
        [ 3.6686,  0.5907,  1.5719],
        [ 0.9564, -0.3670, -1.0033]])

### 加法：in-place，y.add_(x)

In [25]:
a = y.add_(x)
a

tensor([[ 3.8425,  0.9697, -0.0942],
        [-1.3971,  3.9975, -1.3204],
        [ 2.4877,  3.2776,  0.1842],
        [ 6.7805,  0.5506,  2.4003],
        [ 1.6554, -0.9155, -2.5279]])

In [26]:
b = y.add(x)
b

tensor([[ 5.3744,  1.3820, -0.2134],
        [-2.1012,  5.7233, -2.0260],
        [ 3.6544,  4.6674, -0.0873],
        [ 9.8923,  0.5106,  3.2286],
        [ 2.3544, -1.4639, -4.0524]])

In [30]:
a = torch.tensor([3,3])
a

tensor([3, 3])

In [32]:
b = torch.tensor([2,2])
b

tensor([2, 2])

In [33]:
c = a.add(b)
c

tensor([5, 5])

In [34]:
d = a.add_(b)
d

tensor([5, 5])

### 可以使用标准的Numpy类似的索引操作

In [35]:
print(x[:,1])

tensor([ 0.4123,  1.7259,  1.3898, -0.0400, -0.5484])


# Type check

In [3]:
import torch

In [3]:
a = torch.randn(2, 3)
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
print(a)

tensor([[-0.8498, -0.5537, -0.9522],
        [ 0.3787,  1.5810,  0.0051]])


In [6]:
isinstance(a, torch.FloatTensor)

True

In [7]:
isinstance(a, torch.cuda.DoubleTensor)

False

In [11]:
device = torch.device("mps")
x = torch.randn(32, 32, device=device)
x.device

device(type='mps', index=0)

# dim = 0，维度为0，表示标量

In [12]:
a = torch.tensor(2.2)

In [13]:
a.shape

torch.Size([])

In [18]:
a1 = torch.FloatTensor(0,0)

In [19]:
a1

tensor([], size=(0, 0))

In [20]:
a1.shape

torch.Size([0, 0])

In [21]:
torch.Size([])

torch.Size([])

In [22]:
len(a.shape)

0

In [23]:
a.size()

torch.Size([])

In [24]:
torch.Size([])

torch.Size([])

# dim = 1 / rank = 1，维度为1，表示向量

# 在pytorch中，统一称为张量，即tensor

# dim = 1的时候，用在bias中，神经元
# 另一个地方是Linear Input中

In [25]:
torch.tensor([1.1])

tensor([1.1000])

In [26]:
# 使用tensor时，指定了张量的具体数据，即向量的具体数据
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [32]:
# 使用具体类型的tensor时，指定维度为1，即size为1的tensor
a = torch.FloatTensor(1) # 此时数据初始化是random初始化

In [28]:
torch.FloatTensor(2)

tensor([0., 0.])

In [33]:
a.shape

torch.Size([1])

In [29]:
import numpy as np

In [30]:
data = np.ones(2) # 从numpy引入的vector

In [31]:
data

array([1., 1.])

In [34]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [4]:
a=torch.ones(2)

In [5]:
a.shape

torch.Size([2])

# dim = 2

In [6]:
a = torch.randn(2,3)

In [7]:
a

tensor([[ 0.8167,  1.7339, -0.3508],
        [-0.8082, -1.0176,  1.4338]])

In [8]:
a.shape

torch.Size([2, 3])

In [9]:
a.size(0) # 取的行

2

In [10]:
a.size(1)

3

In [11]:
a.shape[0]

2

In [12]:
a.shape[1]

3

# dim = 3 RNN Input Batch, 3维适合NLP的数据处理

In [18]:
a = torch.rand(1,2,3)

In [19]:
a

tensor([[[0.4906, 0.1328, 0.2640],
         [0.1809, 0.1898, 0.3589]]])

In [20]:
a.shape

torch.Size([1, 2, 3])

In [21]:
a[0]

tensor([[0.4906, 0.1328, 0.2640],
        [0.1809, 0.1898, 0.3589]])

In [23]:
list(a.shape)

[1, 2, 3]

# dim = 4 CNN [b, c, h, w]

In [24]:
a = torch.rand(2,3,28,28)

In [25]:
a

tensor([[[[0.4562, 0.3812, 0.8983,  ..., 0.0535, 0.3600, 0.4202],
          [0.3417, 0.4070, 0.4451,  ..., 0.8279, 0.4616, 0.8437],
          [0.5624, 0.0704, 0.7491,  ..., 0.1719, 0.1188, 0.4092],
          ...,
          [0.7197, 0.7153, 0.9823,  ..., 0.7758, 0.1162, 0.0676],
          [0.8647, 0.2782, 0.9560,  ..., 0.0331, 0.0885, 0.9085],
          [0.6522, 0.2101, 0.4493,  ..., 0.9733, 0.5505, 0.7306]],

         [[0.3129, 0.8635, 0.1422,  ..., 0.2384, 0.1105, 0.7220],
          [0.4333, 0.0624, 0.6559,  ..., 0.7960, 0.4020, 0.8272],
          [0.9682, 0.5385, 0.9723,  ..., 0.7974, 0.1918, 0.6974],
          ...,
          [0.8954, 0.6974, 0.1387,  ..., 0.2455, 0.4943, 0.8629],
          [0.2490, 0.6751, 0.7557,  ..., 0.6731, 0.0089, 0.4718],
          [0.9794, 0.4534, 0.8096,  ..., 0.5830, 0.2757, 0.7504]],

         [[0.9518, 0.0424, 0.8541,  ..., 0.8442, 0.7311, 0.3739],
          [0.8348, 0.4423, 0.8196,  ..., 0.5133, 0.3453, 0.7880],
          [0.1145, 0.4845, 0.4310,  ..., 0

In [26]:
a.shape

torch.Size([2, 3, 28, 28])

In [27]:
a[0]

tensor([[[0.4562, 0.3812, 0.8983,  ..., 0.0535, 0.3600, 0.4202],
         [0.3417, 0.4070, 0.4451,  ..., 0.8279, 0.4616, 0.8437],
         [0.5624, 0.0704, 0.7491,  ..., 0.1719, 0.1188, 0.4092],
         ...,
         [0.7197, 0.7153, 0.9823,  ..., 0.7758, 0.1162, 0.0676],
         [0.8647, 0.2782, 0.9560,  ..., 0.0331, 0.0885, 0.9085],
         [0.6522, 0.2101, 0.4493,  ..., 0.9733, 0.5505, 0.7306]],

        [[0.3129, 0.8635, 0.1422,  ..., 0.2384, 0.1105, 0.7220],
         [0.4333, 0.0624, 0.6559,  ..., 0.7960, 0.4020, 0.8272],
         [0.9682, 0.5385, 0.9723,  ..., 0.7974, 0.1918, 0.6974],
         ...,
         [0.8954, 0.6974, 0.1387,  ..., 0.2455, 0.4943, 0.8629],
         [0.2490, 0.6751, 0.7557,  ..., 0.6731, 0.0089, 0.4718],
         [0.9794, 0.4534, 0.8096,  ..., 0.5830, 0.2757, 0.7504]],

        [[0.9518, 0.0424, 0.8541,  ..., 0.8442, 0.7311, 0.3739],
         [0.8348, 0.4423, 0.8196,  ..., 0.5133, 0.3453, 0.7880],
         [0.1145, 0.4845, 0.4310,  ..., 0.0217, 0.3291, 0.

In [28]:
a[1]

tensor([[[0.1860, 0.0600, 0.4104,  ..., 0.8169, 0.0418, 0.9551],
         [0.4527, 0.7469, 0.7646,  ..., 0.9206, 0.6212, 0.5254],
         [0.6496, 0.2645, 0.4763,  ..., 0.0790, 0.5074, 0.1576],
         ...,
         [0.8687, 0.9961, 0.8359,  ..., 0.7189, 0.1520, 0.8814],
         [0.5056, 0.6466, 0.5083,  ..., 0.1068, 0.0595, 0.4687],
         [0.5517, 0.7633, 0.2799,  ..., 0.1548, 0.7480, 0.0419]],

        [[0.2724, 0.3860, 0.6473,  ..., 0.7786, 0.6408, 0.9502],
         [0.8322, 0.5886, 0.1188,  ..., 0.7062, 0.3930, 0.8206],
         [0.4946, 0.2625, 0.6547,  ..., 0.1784, 0.0781, 0.9309],
         ...,
         [0.0080, 0.7677, 0.9934,  ..., 0.1040, 0.9007, 0.9470],
         [0.8418, 0.3591, 0.9626,  ..., 0.0772, 0.9269, 0.7356],
         [0.7641, 0.0111, 0.2855,  ..., 0.1503, 0.9275, 0.6535]],

        [[0.2236, 0.5303, 0.4552,  ..., 0.9443, 0.2910, 0.1466],
         [0.8427, 0.2694, 0.4906,  ..., 0.9278, 0.7315, 0.4168],
         [0.9949, 0.6283, 0.8641,  ..., 0.6974, 0.3355, 0.