# 2.1.1. 入门

In [1]:
import torch
import numpy as np

In [8]:
# 使用arange创建一个行向量x
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# 访问张量的形状
x.shape

torch.Size([12])

In [35]:
# 检查张量元素的总数
x.numel()
# 或
torch.numel(x)

12

In [12]:
# 把张量x从形状为(12,)的行向量转换为形状为(3,4)的矩阵
X = x.reshape(3,4)
display(X,x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
X.shape

torch.Size([3, 4])

In [15]:
X2 = x.reshape(-1,4)
X2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [16]:
X3 = x.reshape(3,-1)
X3

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [23]:
X4 = x.reshape(2,6)
X4

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [34]:
# 创建一个全0，形状为(2,3,4)的张量，二维，三行四列
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [28]:
X5 = torch.zero_(X4) # 将调用它的张量中的所有元素设置为 0。
display(X5,X4)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

In [57]:
# 创建一个全1，形状为(2,3,4)的张量，二维，三行四列
t = torch.ones(2,3,4)
t

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [58]:
t.size()

torch.Size([2, 3, 4])

In [65]:
t1 = t.size(0)
t2 = t.size(1)
t3 = t.size(2)
display(t1, t2, t3)

2

3

4

In [54]:
# 形状为(3,4)的张量，其中每个元素都从均值为0，标准差为1的正态分布
t = torch.randn(3,4)
t

tensor([[ 0.8066, -0.3876,  1.5450,  0.3175],
        [ 0.4747,  0.1055, -0.5043,  0.2616],
        [ 0.7244,  0.1754, -0.5556,  1.2550]])

In [55]:
t.size()

torch.Size([3, 4])

In [40]:
# 张量的维度被称为“轴”（axes），其中每个轴表示一个维度。对于一个多维张量，轴的编号从 0 开始。
x=torch.tensor([[2,1,4,3], [1,2,3,4],[4,3,2,1]])
x

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [41]:
x.shape

torch.Size([3, 4])

In [42]:
x.size()

torch.Size([3, 4])

In [49]:
# 访问轴0（行）
for i in range(x.size(0)): # size(0) 是轴0的大小，即行数
    print(f"第{i}行:", x[i]) # 访问每一行

第0行: tensor([2, 1, 4, 3])
第1行: tensor([1, 2, 3, 4])
第2行: tensor([4, 3, 2, 1])


In [66]:
s = x.size(1)
s

4

In [69]:
# 访问轴1（列）
for j in range(s): # size(1) 是轴1的大小，即列数
    print(f"{j} - :", x[:,j]) # 访问每一列, x[:,j]表示的是从x中选择所有行，并且只选择第j列的数据

0 - : tensor([2, 1, 4])
1 - : tensor([1, 2, 3])
2 - : tensor([4, 3, 2])
3 - : tensor([3, 4, 1])


In [70]:
for j in range(s):
    print(f"所有行第{j}列，",x[[0,1,2],j])

所有行第0列， tensor([2, 1, 4])
所有行第1列， tensor([1, 2, 3])
所有行第2列， tensor([4, 3, 2])
所有行第3列， tensor([3, 4, 1])


In [71]:
x

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [73]:
x[0][0] # 第0行第0列

tensor(2)

In [74]:
x[0][1] # 第0行第1列

tensor(1)

In [75]:
x[1][1] # 第1行第1列

tensor(2)

In [76]:
x[1][3] # 第1行第3列

tensor(4)

# 2.1.2 运算符

In [77]:
x = torch.tensor([1.,2,4,8])
y = torch.tensor([2,2,2,2])

In [78]:
x+y

tensor([ 3.,  4.,  6., 10.])

In [79]:
x-y

tensor([-1.,  0.,  2.,  6.])

In [80]:
x*y

tensor([ 2.,  4.,  8., 16.])

In [81]:
x**y

tensor([ 1.,  4., 16., 64.])

In [82]:
y**x

tensor([  2.,   4.,  16., 256.])

In [84]:
help(torch.exp)

Help on built-in function exp in module torch:

exp(...)
    exp(input, *, out=None) -> Tensor
    
    Returns a new tensor with the exponential of the elements
    of the input tensor :attr:`input`.
    
    .. math::
        y_{i} = e^{x_{i}}
    
    Args:
        input (Tensor): the input tensor.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> torch.exp(torch.tensor([0, math.log(2.)]))
        tensor([ 1.,  2.])



In [83]:
# "按元素"方式运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [85]:
2.7183**8

2981.117410886582

In [87]:
X = torch.arange(12)
X

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
X.dtype

torch.int64

In [89]:
X = torch.arange(12.)
X

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [90]:
X.dtype

torch.float32

In [91]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [92]:
Y = torch.tensor([[2.,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [93]:
Y.dtype

torch.float32

In [100]:
# 连接多个张量，沿行（轴0）
torch.cat((X,Y)) # 默认dim = 0

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [101]:
# 连接多个张量，沿列（轴1）
torch.cat((X,Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [98]:
torch.cat((Y,X),dim=1)

tensor([[ 2.,  1.,  4.,  3.,  0.,  1.,  2.,  3.],
        [ 1.,  2.,  3.,  4.,  4.,  5.,  6.,  7.],
        [ 4.,  3.,  2.,  1.,  8.,  9., 10., 11.]])

In [102]:
X==Y # 对于每个位置，如果X和Y在该位置相等，则新张量中相应荐的值为1，这意味着逻辑语句X＝＝Y在该位置处为真，否则该位置为0

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [104]:
print(True ==1)

True


In [105]:
# 对张量中的所有元素进行求和，会产生一个单元素张量
X.sum()

tensor(66.)

In [106]:
Y.sum()

tensor(30.)

# 2.1.3. 广播机制
### 在某些情况下，即使形状不同，仍然可以通过调用广播机制来执行按元素操作。
### 1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
### 2. 对生成的数组执行按元素操作

In [110]:
# 在沿着数组中长度为1的轴进行广播
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [112]:
a.shape,b.shape

(torch.Size([3, 1]), torch.Size([1, 2]))

In [115]:
x = torch.tensor([1,2])
x

tensor([1, 2])

In [120]:
y = torch.tensor([[1],[2]])
y

tensor([[1],
        [2]])

In [121]:
y.shape

torch.Size([2, 1])

In [122]:
x*y

tensor([[1, 2],
        [2, 4]])

In [123]:
a*b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [124]:
# 在数学中，只有同形状的矩阵才能相加，即同行同列
a+b # 广播为一个更大的3＊2矩阵，即：矩阵a将复制列，矩阵b将复制行，然后再按元素相加

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 2.1.4. 索引和切片
### 就像python中的数组一样，张量中的元素可以通过索引访问。
### 第一个元素的索引是0，最后一个元素索引是-1；可以指定范围以包含第一个元素和最后一个之前的元素。

In [127]:
X,X.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]))

In [126]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [128]:
X[2]

tensor([ 8.,  9., 10., 11.])

In [138]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [139]:
X[1]

tensor([4., 5., 6., 7.])

In [140]:
X[1,2:]

tensor([6., 7.])

In [141]:
X[1:,2:]

tensor([[ 6.,  7.],
        [10., 11.]])

In [143]:
# 指定索引来将元素写入矩阵
# 写入前的X
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [144]:
# 写入后的X
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [145]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [146]:
X[2,1:3] = 7
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  7.,  7., 11.]])

# 2.1.5. 节省内存

In [151]:
before = id(Y)
before

273827036153328

In [152]:
Y += X
b = id(Y)

In [153]:
b

273827036153328

In [148]:
Y.type()

'torch.FloatTensor'

In [149]:
Y = Y+X
id(Y)

273827036153328

In [154]:
Z = torch.zeros_like(Y)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [155]:
id(Z)

273827036155632

In [156]:
Z[:]=X+Y # 使用切处表示法将操作的结果分配给先前分配的数组

In [157]:
id(Z)

273827036155632

In [158]:
# 切片在列表中的工作方式
# 对于列表，切片操作会创建一个新的列表对象，但这个新列表内部的元素实际上对原始列表元素的引用。
o = [1,2,3,4,5,6]

In [159]:
o

[1, 2, 3, 4, 5, 6]

In [163]:
id(o)

273827048327488

In [160]:
s = o[1:4]

In [161]:
s

[2, 3, 4]

In [164]:
id(s)

273827049411392

In [162]:
o

[1, 2, 3, 4, 5, 6]

In [165]:
o[2] = 99

In [166]:
o

[1, 2, 99, 4, 5, 6]

In [167]:
s

[2, 3, 4]

# 2.1.6. 转换为其他Python对象

In [169]:
# torch和numpy数组将共享它们底层内存，操作更改一个张量也会同时更改另一个张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [170]:
# 将大小为1的张量转换为Python标题，可以调用item函数或python内置函数
a = torch.tensor([3.5])

In [171]:
a

tensor([3.5000])

In [172]:
a.item()

3.5

In [173]:
float(a),int(a)

(3.5, 3)

# 2.1.7. 小结

In [175]:
# 深度学习存储和操作数据的主要接口是张量（n维数组）。它提供了各种功能，包括基本数学运算，广播，索引，切片，
# 内存节省和转换其他Python对象

# 2.1.8. 练习

In [179]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [180]:
Y = torch.tensor([[2.,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [181]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [182]:
X>Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [183]:
X<Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [210]:
a = torch.tensor([[[1,2]],[[2,3]],[[3,4]]])
a

tensor([[[1, 2]],

        [[2, 3]],

        [[3, 4]]])

In [211]:
a.shape

torch.Size([3, 1, 2])

In [212]:
b = torch.tensor([[[2,],[4,]]])
b

tensor([[[2],
         [4]]])

In [213]:
b.shape

torch.Size([1, 2, 1])

In [214]:
a+b

tensor([[[3, 4],
         [5, 6]],

        [[4, 5],
         [6, 7]],

        [[5, 6],
         [7, 8]]])