## 线性回归作业
### 气温会随着海拔高度的升高而降低，我们可以通过测量不同海拔高度的气温来预测海拔高度和气温的关系。
### 假设海拔高度和气温的关系可以使用如下公式表达：y(气温) = w * x(海拔) + b
### 理论上来讲，确定以上公式w和b的值只需在两个不同高度测试，就可以算出来w和b的值了。
### 但是由于所有的设备都是有误差的，而使用更多的高度测试的值可以使得预测的值更加准确。
### 下面提供了在9个不同高度测量的气温值，请根据（正规方程）方法预测w和b的值。根据这个公式，预测一下在8000m的海拔，气温会是多少？
####    height       temperature
####    0.0             12.834044
####    500.0         10.190649
####    1000.0       5.500229
####    1500.0       2.854665
####    2000.0       -0.706488
####    2500.0       -4.065323
####    3000.0       -7.127480
####    3500.0       -10.058879
####    4000.0       -13.206465

In [7]:
import numpy as np

height_temperature_map = {"height": "temperature",
                          "0.0   ":  "12.834044",
                          "500.0 ": "10.190649",
                          "1000.0":  "5.500229",
                          "1500.0": "2.854665",
                          "2000.0": "-0.706488",
                          "2500.0": "-4.065323",
                          "3000.0": "-7.127480",
                          "3500.0": "-10.058879",
                          "4000.0": "-13.206465",
                         }
height_temperature_map

{'height': 'temperature',
 '0.0   ': '12.834044',
 '500.0 ': '10.190649',
 '1000.0': '5.500229',
 '1500.0': '2.854665',
 '2000.0': '-0.706488',
 '2500.0': '-4.065323',
 '3000.0': '-7.127480',
 '3500.0': '-10.058879',
 '4000.0': '-13.206465'}

In [40]:
X = np.array([[0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]])
X

array([[   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]])

In [41]:
X.shape

(1, 9)

In [42]:
y = np.array([[12.834044, 10.190649, 5.500229, 2.854665, -0.706488, -4.065323, -7.127480, -10.058879, -13.206465]])
y

array([[ 12.834044,  10.190649,   5.500229,   2.854665,  -0.706488,
         -4.065323,  -7.12748 , -10.058879, -13.206465]])

In [43]:
y.shape

(1, 9)

### 方法一，用正规方程解答

In [44]:
A = X.T.dot(X)
A

array([[       0,        0,        0,        0,        0,        0,
               0,        0,        0],
       [       0,   250000,   500000,   750000,  1000000,  1250000,
         1500000,  1750000,  2000000],
       [       0,   500000,  1000000,  1500000,  2000000,  2500000,
         3000000,  3500000,  4000000],
       [       0,   750000,  1500000,  2250000,  3000000,  3750000,
         4500000,  5250000,  6000000],
       [       0,  1000000,  2000000,  3000000,  4000000,  5000000,
         6000000,  7000000,  8000000],
       [       0,  1250000,  2500000,  3750000,  5000000,  6250000,
         7500000,  8750000, 10000000],
       [       0,  1500000,  3000000,  4500000,  6000000,  7500000,
         9000000, 10500000, 12000000],
       [       0,  1750000,  3500000,  5250000,  7000000,  8750000,
        10500000, 12250000, 14000000],
       [       0,  2000000,  4000000,  6000000,  8000000, 10000000,
        12000000, 14000000, 16000000]])

In [45]:
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w

LinAlgError: Singular matrix