In [16]:
from sklearn.datasets import load_iris
from sklearn import tree, metrics
from sklearn.metrics import confusion_matrix, precision_score, recall_score
from sklearn.metrics import f1_score, accuracy_score, accuracy_score, classification_report
from sklearn.tree import plot_tree
from IPython.core.interactiveshell import InteractiveShell
import matplotlib.pyplot as plt
InteractiveShell.ast_node_interactivity = 'all'

## 加载iris数据集

In [2]:
iris = load_iris()
x = iris.data
y = iris.target

print('The iris feature name:',iris.feature_names)
x[:10]

The iris feature name: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [3]:
print('The iris target name:',iris.target_names)
y

The iris target name: ['setosa' 'versicolor' 'virginica']


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 拆分训练集和测试集

In [4]:
from sklearn import model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=123456)

## 用DecisionTreeClassifier训练决策树模型

In [5]:
dtree = tree.DecisionTreeClassifier(max_depth=3)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [6]:
dtree.classes_
dtree.feature_importances_
dtree.max_features_
dtree.n_classes_
dtree.n_outputs_
dtree.tree_

array([0, 1, 2])

array([0.02913253, 0.        , 0.41379753, 0.55706995])

4

3

1

## 用测试集验证

In [7]:
pred = dtree.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.87      0.87      0.87        15
           2       0.87      0.87      0.87        15

    accuracy                           0.91        45
   macro avg       0.91      0.91      0.91        45
weighted avg       0.91      0.91      0.91        45



## 可视化的查看决策树结果

### 在jupyter中直接显示图片

In [10]:
import pydotplus
import graphviz
from IPython.display import Image

dot_data = tree.export_graphviz(dtree, out_file=None, 
                                feature_names=iris.feature_names,
                                class_names=iris.target_names,
                                filled=True, rounded=True,
                                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data)


In [17]:
plt.figure(figsize=(60,30))

<Figure size 6000x3000 with 0 Axes>

<Figure size 6000x3000 with 0 Axes>

In [22]:
plot_tree(dtree, feature_names = X_train.columns, filled= True)

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [13]:
pip list

Package                           Version
--------------------------------- ------------
aext_assistant                    0.4.0
aext_assistant_server             0.4.0
aext_core                         0.4.0
aext_core_server                  0.4.0
aext_shared                       0.4.0
aiobotocore                       2.7.0
aiofiles                          22.1.0
aiohttp                           3.9.3
aioitertools                      0.7.1
aiosignal                         1.2.0
aiosqlite                         0.18.0
alabaster                         0.7.12
altair                            5.0.1
anaconda-anon-usage               0.4.3
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.5.0
anaconda-navigator                2.6.0
anaconda-project                  0.11.1
anyio                             4.2.0
appdirs                           1.4.4
applaunchservices                 0.3.0
appnope                   

Note: you may need to restart the kernel to use updated packages.
