# 标量由只有一个元素的张量表示

In [1]:
import torch

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

# 你可以将向量视为标题值组成的列表

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

# 通过张量的索引来访问任一元素

In [4]:
x[3]

tensor(3)

# 访问张量的长度

In [5]:
len(x)

4

# 只有一个轴的张量，形状只有一个元素

In [7]:
x2 = x.shape
x2

torch.Size([4])

In [8]:
len(x2)

1

# 通过指定两个分量m和n来创建一个形状为m*n的矩阵

In [9]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

# 矩阵的转置

In [13]:
A.shape

torch.Size([5, 4])

# 对称矩阵（symmetric matrix）A等于其转置: A = A

In [14]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [15]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

# 向量是标量的推广，矩阵是向量的推广，可以构建具有更多轴的数据结构

In [16]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

# 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [19]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone() #通过分配新内存，将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

# 两个矩阵的按元素乘法称为 哈达玛积，数学符号⊙

In [20]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [22]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, 

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),)

In [23]:
a1 = a * X
a1

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [24]:
a1.shape

torch.Size([2, 3, 4])

TypeError: 'torch.Size' object is not callable

# 计算其元素的和

In [26]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

# 表示任意形状张量的元素和

In [27]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [28]:
a = torch.ones((2,5,4))

In [29]:
a.shape

torch.Size([2, 5, 4])

In [31]:
a.sum(axis=1).shape

torch.Size([2, 4])