In [1]:
import numpy as np

In [2]:
# 创建一个二维向量
x = np.array([1,2])
x

array([1, 2])

In [3]:
# 向量加法
x1 = np.array([1,2])
x2 = np.array([2,3])
x1+x2

array([3, 5])

In [4]:
# 向量数乘
x1 = np.array([1,2])
3*x1

array([3, 6])

In [5]:
# 创建一个三维向量
x = np.array([1,2,3])
x

array([1, 2, 3])